import {
  Menu,
  User,
  Heart,
  Settings,
  LogOut,
  Clock,
  Plus,
  X,
  Tag,
  Search,
  Trash2,
  Check,
  Upload,
  Save,
  ImageIcon,
  Loader2,
} from "lucide-react"

import { FaUser, FaPhoneAlt } from "react-icons/fa"

import {
  FaTelegram,
  FaWhatsapp,
  FaYoutube,
  FaTwitter,
  FaInstagram,
  FaFacebookF,
  FaLocationDot,
  FaRegCalendar,
  FaCloudArrowUp,
} from "react-icons/fa6"
import { TiSocialLinkedin } from "react-icons/ti"
import { IoMdMail } from "react-icons/io"

export const Icons = {
  account: FaUser,
  telegram: FaTelegram,
  whatsapp: FaWhatsapp,
  youtube: FaYoutube,
  twitter: FaTwitter,
  instagram: FaInstagram,
  facebook: FaFacebookF,
  linkedin: TiSocialLinkedin,
  menu: Menu,
  phone: FaPhoneAlt,
  email: IoMdMail,
  location: FaLocationDot,
  user: User,
  heart: Heart,
  settings: Settings,
  logout: LogOut,
  calendar: FaRegCalendar,
  clock: Clock,
  plus: Plus,
  x: X,
  tag: Tag,
  trash2: Trash2,
  check: Check,
  uploadImage: FaCloudArrowUp,
  upload: Upload,
  save: Save,
  imageIcon: ImageIcon,
  loader2: Loader2,
}
