import { Icons } from "@/components/shared/icons"

export const navigationItems = [
  { label: "مدونات", href: "/blogs" },
  { label: "اكتب معنا", href: "/write-with-us" },
  { label: "من نحن", href: "/about-us" },
  { label: "فعاليات", href: "/events" },
  { label: "تواصل معنا", href: "/contact-us" },
]

export const navigationsIconsItems = [
  {
    label: "telegram",
    icon: Icons.telegram,
    href: "https://telegram.org",
  },
  {
    label: "whatsapp",
    icon: Icons.whatsapp,
    href: "https://whatsapp.com",
  },
  {
    label: "youtube",
    icon: Icons.youtube,
    href: "https://youtube.com",
  },
  {
    label: "linkedin",
    icon: Icons.linkedin,
    href: "https://linkedin.com",
  },
  {
    label: "twitter",
    icon: Icons.twitter,
    href: "https://twitter.com",
  },
  {
    label: "instagram",
    icon: Icons.instagram,
    href: "https://instagram.com",
  },
  {
    label: "facebook",
    icon: Icons.facebook,
    href: "https://facebook.com",
  },
]

export const instituteLinks = [
  { label: "من نحن", href: "/about-us" },
  { label: "تواصل معنا", href: "/contact-us" },
  { label: "اكتب معنا", href: "/write-with-us" },
  { label: "فعاليات المعهد", href: "/events" },
]

export const reportsLinks = [
  { label: "ركن شهري", href: "/blogs" },
  { label: "ركن شهري", href: "/blogs" },
]

export const researchLinks = [
  { label: "الأبحاث المتعلقة بالدين", href: "/blogs" },
  {
    label: "الأبحاث السياسية",
    href: "/blogs",
    underlined: true,
  },
  { label: "العلاقات الدولية", href: "/blogs" },
  {
    label: "العلاقات الإستراتيجية",
    href: "/blogs",
    underlined: true,
  },
]

export const ImageWithDescriptionItems = [
  {
    image: "/assets/about-us.jpg",
    alt: "About Us",
    title: "من نحن",
    description:
      "نحن نؤمن بأن الكلمات لها القوة لتغيير العالم. نحن [اسم موقعك]، مكان يسعى لنقل الأخبار والقضايا الهامة بأسلوب متميز وإلهامي.",
  },
  {
    image: "/assets/write-with-us.jpg",
    alt: "Write With Us",
    title: "اكتب معنا",
    description:
      "هل ترغب في مشاركة مهاراتك ككاتب مع مجتمعنا؟ نحن نبحث دائمًا عن مواهب جديدة لإثراء محتوانا. إذا كنت تمتلك شغفًا للكتابة وترغب في الانضمام إلى فريقنا، فنحن نرحب بك!",
    button: "ابدأ الكتابة الآن!",
    link: "/write-with-us",
  },
  {
    image: "/assets/about-us.jpg",
    alt: "Home",
    title: " أيـقِظ فضولك مع معهدي",
    description:
      "في عالم يتغيّر باستمرار، يصبح تخصيص لحظة للقراءة والتفكير والكتابة فعلًا من الوعي. هذا المدوّنة هي مساحتك الخاصة للإلهام، حيث نكتب بكل شغف لنغذّي عقلك ونمنحك لحظات من التأمّل وسط بساطة الحياة اليومية. أهلاً بك في عالم حيث للكلمات معنى، وللأفكار حياة.",
  },
  {
    image: "/assets/inscription.jpg",
    alt: "Inscription",
    title: "اشتراك ",
    description:
      "هل ترغب في مشاركة مهاراتك ككاتب مع مجتمعنا؟ نحن نبحث دائمًا عن مواهب جديدة لإثراء محتوانا. إذا كنت تمتلك شغفًا للكتابة وترغب في الانضمام إلى فريقنا، فنحن نرحب بك!",
    button: "سجّل اليوم!",
    link: "/sign-up",
  },
]

export const fileTypes = {
  "image/jpeg": [".jpeg", ".jpg"],
  "image/png": [".png"],
  "image/webp": [".webp"],
  "image/gif": [".gif"],
  "image/bmp": [".bmp"],
  "image/svg+xml": [".svg"],
  "image/tiff": [".tif", ".tiff"],
  "image/x-icon": [".ico"],
  "image/heif": [".heif"],
  "image/heic": [".heic"],
  "image/avif": [".avif"],
}

export const profileNavigationItems = [
  {
    href: "/profile",
    label: "معلوماتي",
    icon: Icons.user,
  },
  {
    href: "/my-blogs",
    label: "قائمة مدوناتي",
    icon: Icons.notbook,
  },
]

export const data = {
  navMain: [
    {
      title: "المستخدمين",
      url: "/dashboard/users",
      icon: Icons.iconUsers,
    },
    {
      title: "طلبات",
      url: "/dashboard/applications",
      icon: Icons.handHelping,
    },
    {
      title: "فعاليات",
      url: "/dashboard/events",
      icon: Icons.calendar2,
    },
    {
      title: "فئات",
      url: "/dashboard/categories",
      icon: Icons.tag,
    },
  ],

  documents: [
    {
      name: "أبحاث",
      url: "/dashboard/recherches",
      icon: Icons.microscope,
    },
    {
      name: "تقارير",
      url: "/dashboard/rapports",
      icon: Icons.iconReport,
    },
    {
      name: "مقالات",
      url: "/dashboard/articles",
      icon: Icons.newspaper,
    },
  ],
}

export const faqItems = [
  {
    id: "item-1",
    question: "كيف يمكنني الكتابة؟",
    answer: "يجب عليك إرسال طلب وسيقوم المشرف بمراجعته وقبوله.",
  },
  {
    id: "item-2",
    question: "كيف يمكنني التسجيل في المنصة؟",
    answer:
      "يمكنك التسجيل مباشرة كمستخدم لقراءة المدونات والاستفادة من المحتوى المتاح.",
  },
  {
    id: "item-3",
    question: "هل المدونات التي أكتبها تخضع للرقابة؟",
    answer:
      "نعم، جميع المدونات تخضع للمراجعة ولا يتم نشرها إلا بعد موافقة المشرف.",
  },
  {
    id: "item-4",
    question: "هل تردون بسرعة على الاستفسارات؟",
    answer:
      "نعم، نحن نحرص على الرد السريع على جميع الاستفسارات والمساعدة في أقرب وقت ممكن.",
  },
]

// Interface pour les catégories dynamiques
export interface CategoryType {
  id: string
  name: string
}

export const notFoundLinks = [
  {
    name: "مدونات",
    href: "/blogs",
    description: "اكتشف مدوناتنا المتنوعة.",
    icon: Icons.newspaper,
  },
  {
    name: "فعاليات",
    href: "/events",
    description: "تابع أحدث فعالياتنا القادمة.",
    icon: Icons.calendar2,
  },
  {
    name: "اكتب معنا",
    href: "/write-with-us",
    description: "ساهم بمقالاتك وأفكارك معنا.",
    icon: Icons.pencil,
  },
  {
    name: "تواصل معنا",
    href: "/contact-us",
    description: "تواصل معنا لأي استفسار.",
    icon: Icons.iconUsers,
  },
]

export const NamesCountry: Record<string, string> = {
  AD: "أندورا",
  AE: "الإمارات العربية المتحدة",
  AF: "أفغانستان",
  AG: "أنتيغوا وبربودا",
  AI: "أنغيلا",
  AL: "ألبانيا",
  AM: "أرمينيا",
  AO: "أنغولا",
  AQ: "أنتاركتيكا",
  AR: "الأرجنتين",
  AS: "ساموا الأمريكية",
  AT: "النمسا",
  AU: "أستراليا",
  AW: "أروبا",
  AZ: "أذربيجان",
  BA: "البوسنة والهرسك",
  BB: "بربادوس",
  BD: "بنغلاديش",
  BE: "بلجيكا",
  BF: "بوركينا فاسو",
  BG: "بلغاريا",
  BH: "البحرين",
  BI: "بوروندي",
  BJ: "بنين",
  BM: "برمودا",
  BN: "بروناي",
  BO: "بوليفيا",
  BR: "البرازيل",
  BS: "الباهاما",
  BT: "بوتان",
  BW: "بوتسوانا",
  BY: "بيلاروس",
  BZ: "بليز",
  CA: "كندا",
  CD: "جمهورية الكونغو الديمقراطية",
  CF: "جمهورية أفريقيا الوسطى",
  CG: "الكونغو",
  CH: "سويسرا",
  CI: "ساحل العاج",
  CL: "تشيلي",
  CM: "الكاميرون",
  CN: "الصين",
  CO: "كولومبيا",
  CR: "كوستاريكا",
  CU: "كوبا",
  CV: "الرأس الأخضر",
  CY: "قبرص",
  CZ: "التشيك",
  DE: "ألمانيا",
  DJ: "جيبوتي",
  DK: "الدنمارك",
  DM: "دومينيكا",
  DO: "جمهورية الدومينيكان",
  DZ: "الجزائر",
  EC: "الإكوادور",
  EE: "إستونيا",
  EG: "مصر",
  ER: "إريتريا",
  ES: "إسبانيا",
  ET: "إثيوبيا",
  FI: "فنلندا",
  FJ: "فيجي",
  FM: "ميكرونيزيا",
  FR: "فرنسا",
  GA: "الغابون",
  GB: "المملكة المتحدة",
  GD: "غرينادا",
  GE: "جورجيا",
  GH: "غانا",
  GM: "غامبيا",
  GN: "غينيا",
  GQ: "غينيا الاستوائية",
  GR: "اليونان",
  GT: "غواتيمالا",
  GW: "غينيا بيساو",
  GY: "غويانا",
  HN: "هندوراس",
  HR: "كرواتيا",
  HT: "هايتي",
  HU: "المجر",
  ID: "إندونيسيا",
  IE: "أيرلندا",
  IL: "إسرائيل",
  IN: "الهند",
  IQ: "العراق",
  IR: "إيران",
  IS: "أيسلندا",
  IT: "إيطاليا",
  JM: "جامايكا",
  JO: "الأردن",
  JP: "اليابان",
  KE: "كينيا",
  KG: "قيرغيزستان",
  KH: "كمبوديا",
  KI: "كيريباتي",
  KM: "جزر القمر",
  KN: "سانت كيتس ونيفيس",
  KP: "كوريا الشمالية",
  KR: "كوريا الجنوبية",
  KW: "الكويت",
  KY: "جزر كايمان",
  KZ: "كازاخستان",
  LA: "لاوس",
  LB: "لبنان",
  LC: "سانت لوسيا",
  LI: "ليختنشتاين",
  LK: "سريلانكا",
  LR: "ليبيريا",
  LS: "ليسوتو",
  LT: "ليتوانيا",
  LU: "لوكسمبورغ",
  LV: "لاتفيا",
  LY: "ليبيا",
  MA: "المغرب",
  MC: "موناكو",
  MD: "مولدوفا",
  ME: "الجبل الأسود",
  MG: "مدغشقر",
  MH: "جزر مارشال",
  MK: "مقدونيا الشمالية",
  ML: "مالي",
  MM: "ميانمار",
  MN: "منغوليا",
  MO: "ماكاو",
  MR: "موريتانيا",
  MT: "مالطا",
  MU: "موريشيوس",
  MV: "المالديف",
  MW: "مالاوي",
  MX: "المكسيك",
  MY: "ماليزيا",
  MZ: "موزمبيق",
  NA: "ناميبيا",
  NE: "النيجر",
  NG: "نيجيريا",
  NI: "نيكاراغوا",
  NL: "هولندا",
  NO: "النرويج",
  NP: "نيبال",
  NR: "ناورو",
  NU: "نيوي",
  NZ: "نيوزيلندا",
  OM: "عمان",
  PA: "بنما",
  PE: "بيرو",
  PF: "بولينيزيا الفرنسية",
  PG: "بابوا غينيا الجديدة",
  PH: "الفلبين",
  PK: "باكستان",
  PL: "بولندا",
  PT: "البرتغال",
  PW: "بالاو",
  PY: "باراغواي",
  QA: "قطر",
  RO: "رومانيا",
  RS: "صربيا",
  RU: "روسيا",
  RW: "رواندا",
  SA: "السعودية",
  SB: "جزر سليمان",
  SC: "سيشل",
  SD: "السودان",
  SE: "السويد",
  SG: "سنغافورة",
  SI: "سلوفينيا",
  SK: "سلوفاكيا",
  SL: "سيراليون",
  SM: "سان مارينو",
  SN: "السنغال",
  SO: "الصومال",
  SR: "سورينام",
  SS: "جنوب السودان",
  ST: "ساو تومي وبرينسيبي",
  SV: "السلفادور",
  SY: "سوريا",
  SZ: "إسواتيني",
  TD: "تشاد",
  TG: "توغو",
  TH: "تايلاند",
  TJ: "طاجيكستان",
  TL: "تيمور الشرقية",
  TM: "تركمانستان",
  TN: "تونس",
  TO: "تونغا",
  TR: "تركيا",
  TT: "ترينيداد وتوباغو",
  TV: "توفالو",
  TZ: "تنزانيا",
  UA: "أوكرانيا",
  UG: "أوغندا",
  US: "الولايات المتحدة",
  UY: "أوروغواي",
  UZ: "أوزبكستان",
  VA: "الفاتيكان",
  VC: "سانت فنسنت والغرينادين",
  VE: "فنزويلا",
  VN: "فيتنام",
  VU: "فانواتو",
  WS: "ساموا",
  YE: "اليمن",
  ZA: "جنوب أفريقيا",
  ZM: "زامبيا",
  ZW: "زيمبابوي",
}
